spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.telemetry.serdes.deserializer.SensorEventDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.telemetry.serdes.serializer.SensorsSnapshotSerializer
      acks: all
      retries: 3
      batch-size: 16384
      properties:
        linger.ms: 10
        buffer.memory: 33554432

kafka:
  topics:
    sensor-events: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1

server:
  port: 8082

logging:
  level:
    ru.yandex.practicum.telemetry.aggregator: DEBUG
    org.apache.kafka: WARN